# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - VT60003CEM-portfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_fdc6a8dbde584bebb597c67248ceb216 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_09c4c2b0dbec42eaa58a65f407c067f4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fdc6a8dbde584bebb597c67248ceb216 }}/ikouhaha888/profolio_frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'VT60003CEM-portfolio'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f043d2ae425c44e387104d3d8f90bae0 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fdc6a8dbde584bebb597c67248ceb216 }}/ikouhaha888/profolio_frontend:${{ github.sha }}'